//! @file Configure.h
//! This file is generated by CMake. Do not modify.

#ifndef ATL_CONFIGURE_H
#define ATL_CONFIGURE_H

#define ATL_VERSION_MAJOR 1
#define ATL_VERSION_MINOR 0
#define ATL_VERSION "1.0"

#define ATL_FILESYSTEM_HEADER filesystem
#define ATL_FILESYSTEM_NAMESPACE std::filesystem
#define ATL_FILESYSTEM_HAVE_FS TRUE
#define ATL_FILESYSTEM_INCLUDE <filesystem>

#endif // ATL_CONFIGURE_H
